[package]
name = "postgres-ost"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
itertools = "0.14.0"
postgres = "0.19.10"
sqlparser = { version = "0.56.0", features = ["visitor"] }
