name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install wal2json and configure PostgreSQL for logical replication
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-15-wal2json
          echo "wal_level = logical" | sudo tee -a /etc/postgresql/15/main/postgresql.conf
          echo "shared_preload_libraries = 'wal2json'" | sudo tee -a /etc/postgresql/15/main/postgresql.conf
          sudo systemctl restart postgresql
      - name: Start PostgreSQL
        run: sudo systemctl start postgresql
      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            pg_isready -U postgres && break
            sleep 1
          done
      - name: Set up test database user
        run: |
          sudo -u postgres psql -c "CREATE USER post_test WITH SUPERUSER PASSWORD 'postgres';"
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libpq-dev
      - name: Build
        run: cargo build --all --verbose
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Set POSTGRES_OST_TEST_DB_URL for tests
        run: echo "POSTGRES_OST_TEST_DB_URL=postgres://post_test:postgres@localhost/postgres" >> $GITHUB_ENV
      - name: Run tests
        env:
          PGUSER: post_test
          PGPASSWORD: postgres
          PGHOST: localhost
        run: cargo test --all -- --nocapture
